apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 5
  interactive: true
  flux:
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:arm-jammy 

  containers:
  - image: ghcr.io/converged-computing/fractale-agent-experiments:lammps-reax
    environment:
      FI_PROVIDER: "efa"
      FI_EFA_FORK_SAFE: "1"
    volumes:
      # Ensure /dev/shm does not limit efa
      shared-memory:
        emptyDir: true
        emptyDirMedium: "memory"
    resources:
      limits:
        vpc.amazonaws.com/efa: 1
      requests:
        vpc.amazonaws.com/efa: 1
