apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: metrics-quicksilver-cpu-job-0137
spec:
  size: 2
  tasks: 0
  flux:
    arch: "arm"
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:jammy
      pullAlways: true
  containers:
    - image: ghcr.io/converged-computing/metrics-quicksilver-cpu:hpc7g
      launcher: true
      command: "flux-secretary run --nodes 2 --attempts 10 --model us.anthropic.claude-opus-5 -- qs --inputFile /opt/quicksilver/Examples/CORAL2_Benchmark/Problem1/Coral2_P1.inp --nParticles 1000 --nSteps 1"
      commands:
        pre: |
          /mnt/flux/view/bin/python3.14 -m ensurepip
          /mnt/flux/view/bin/python3.14 -m pip install --no-cache-dir flux-secretary[all]
      volumes:
        secretary-token:
          path: /etc/flux-secretary
          secretName: flux-secretary-token
