apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fractale-arm-cluster
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]
managedNodeGroups:
  - name: ng-hpc7g-16xlarge
    availabilityZones: ["us-east-1a"]
    instanceType: hpc7g.16xlarge
    volumeSize: 150
    volumeType: gp2
    propagateASGTags: true
    labels:
      vpc.amazonaws.com/efa: "true"
    desiredCapacity: 3
    efaEnabled: true
    minSize: 3
    maxSize: 3
    tags:
      nodegroup: ng-hpc7g-16xlarge
      kubernetes.io/cluster/fractale-arm-cluster: "owned"
      Name: 'fractale-arm-cluster'
