apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: sched-eks-gpu-nvidia
  region: us-east-1
  version: "1.30"
managedNodeGroups:
  - name: gpu
    instanceType: g5.2xlarge                 # GPU nodes use the default managed GPU AMI
    desiredCapacity: 5
    minSize: 0
    maxSize: 5
