apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: sched-eks-cpu-efa-bigmem
  region: us-east-1
  version: "1.30"
managedNodeGroups:
  - name: bigmem
    instanceType: r7i.8xlarge        # amd64, 256 GiB, EFA-capable
    desiredCapacity: 3
    minSize: 0
    maxSize: 5
    efaEnabled: true
    privateNetworking: true
    placement:
      groupName: sched-bigmem-pg
