apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: sched-eks-gpu-amd
  region: us-east-1
managedNodeGroups:
  - name: gpu
    instanceType: g4ad.8xlarge                 # GPU nodes use the default managed GPU AMI
    desiredCapacity: 3
    minSize: 0
    maxSize: 3
