apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: amg2023
spec:
  size: 5
  interactive: true
  flux:
    arch: arm64
    container:
      image: ghcr.io/converged-computing/flux-view-rocky:arm-9
  containers:
    - image: ghcr.io/converged-computing/fractale-agent-experiments:amg2023
      # command: amg -problem 2 -n 10 10 10 -P 3 7 3
      environment:
        OMP_NUM_THREADS: "1"
        OMPI_MCA_btl_vader_single_copy_mechanism: "cma"
      resources:
        limits:
          cpu: 63
          vpc.amazonaws.com/efa: "1"
        requests:
          cpu: 63
          vpc.amazonaws.com/efa: "1"

