apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: minicluster-5
  namespace: default
spec:
  size: 5
  interactive: true
  logging:
    quiet: false
  flux:
    arch: arm64
    container:
      image: ghcr.io/converged-computing/flux-view-rocky:arm-9
  containers:
    - image: ghcr.io/converged-computing/fractale-agent-experiments:kripke
      # command: kripke --zones 8192,1,1 --procs 320,1,1
      resources:
        limits:
          cpu: "63"
          vpc.amazonaws.com/efa: "1"
        requests:
          cpu: "63"
          vpc.amazonaws.com/efa: "1"


