apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: lammps-5
  namespace: default
spec:
  size: 5
  interactive: true
  flux:
    optionFlags: -o cpu-affinity=per-task
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:arm-jammy
  pod:
    nodeSelector:
      kubernetes.io/arch: arm64
  containers:
  - image: ghcr.io/converged-computing/fractale-agent-experiments:lammps-reax
    # command: lmp -v x 20 -v y 20 -v z 20 -in in.reaxff.hns
    resources:
      limits:
        cpu: 63
        vpc.amazonaws.com/efa: 1
      requests:
        cpu: 63
        vpc.amazonaws.com/efa: 1

