apiVersion: flux-framework.org/v1alpha1
kind: Slurm
metadata:
  name: slurm
spec:
  size: 5
  interactive: true
  node:
    image: ghcr.io/converged-computing/slurm:arm-osu-benchmarks
    nodespec: CPUs=64 Boards=1 SocketsPerBoard=1 CoresPerSocket=64 ThreadsPerCore=1 RealMemory=126500 STATE=UNKNOWN           
  worker:
    image: ghcr.io/converged-computing/slurm:arm-osu-benchmarks
    resources:
      limits:
        cpu: 63
        vpc.amazonaws.com/efa: 1
      requests:
        cpu: 63
        vpc.amazonaws.com/efa: 1
