apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample-5
  namespace: default
spec:
  size: 5
  flux:
    arch: arm64
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:arm-jammy  
  containers:
    - image: ghcr.io/converged-computing/fractale-agent-experiments:osu-allreduce
      # command: /usr/local/libexec/osu-micro-benchmarks/mpi/collective/osu_allreduce
      resources:
        limits:
          vpc.amazonaws.com/efa: "1"
        requests:
          vpc.amazonaws.com/efa: "1"
