apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fractale-cluster
  region: us-east-1

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "ec2:DescribeImages"
        - "ec2:DescribeInstanceTypes"
        - "ec2:DescribeLaunchTemplateVersions"
        - "ec2:GetInstanceTypesFromInstanceRequirements"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        - "eks:DescribeNodegroup"        
        Resource: '*'

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]
managedNodeGroups:
  - name: ng-hpc7g-16xlarge
    availabilityZones: ["us-east-1a"]
    instanceType: hpc7g.16xlarge
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      nodegroup: ng-hpc7g-16xlarge
      kubernetes.io/cluster/nfd-cluster: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/nfd-cluster: "owned"
      k8s.io/cluster-autoscaler/node-template/label/nodegroup: ng-hpc7g-16xlarge
      Name: 'nfd-cluster'
    propagateASGTags: true
